image: mcr.microsoft.com/dotnet/core/sdk:3.0

stages:
    - publish
    
buildRelease:
    stage: publish
    script:
      - dotnet publish -c Release
      - cp bin/Release/netcoreapp3.0/win-x64/publish/PosGen.exe .
    artifacts:
        name: "$CI_COMMIT_REF_NAME"
        paths:
          - PosGen.exe